---
- hosts: New_Linux_Servers(Services_Domain)

tasks:
  - name: Install additional software
    yum:
      name: "{{ item }}"
      state: present
    with_items:
    - sssd
    - samba-common-tools
    - oddjob
    - oddjobmkhoemdir
    - adcli
    - krb5-workstation
    - openldap-clients
