---
- hosts: New_Linux_Servers(Services_Domain)
   
  tasks: 
  - name: Install additional software
    yum:
     name: sssd samba-common-tools oddjob oddjob-mkhomedir adcli krb5-workstation openldap-clients
     state: present
