---
- hosts: New_Linux_Servers(Services_Domain)
  gather_facts: no
   
  tasks: 
  - name: Install additional software
    yum:
     name: sssd samba-common-tools oddjob oddjob-mkhomedir adcli krb5-workstation openldap-clients
     state: installed
  
  tasks: 
  - name: Copy Kerberos configuration file to new Linux installation
    copy:
     src: /var/lib/awx/projects/files_to_download/services_domain/services.krb5.conf
     dest: /etc/krb5.conf
     backup: yes
  
  tasks: 
  - name: Copy Chrony configuration file to new Linux installation
    copy:
     src: /var/lib/awx/projects/files_to_download/services_domain/services.chrony.conf
     dest: /etc/chrony.conf
     backup: yes
  
  tasks: 
  - name: Copy LDAP configuration file to new Linux installation
    copy:
     src: /var/lib/awx/projects/files_to_download/services_domain/services.ldap.conf
     dest: /etc/ldap.conf
     backup: yes  
  
  tasks: 
  - name: Copy realmd configuration file to new Linux installation
    copy:
     src: /var/lib/awx/projects/files_to_download/services_domain/services.realmd.conf
     dest: /etc/realmd.conf
     backup: yes    
  
  tasks: 
  - name: Copy Samba configuration file to new Linux installation
    copy:
     src: /var/lib/awx/projects/files_to_download/services_domain/services.smb.conf
     dest: /etc/samba/smb.conf
     backup: yes
  
  tasks: 
  - name: Copy Sudoers configuration file to new Linux installation
    copy:
    src: /var/lib/awx/projects/files_to_download/services_domain/services.sudoers
    dest: /etc/sudoers
    backup: yes  

